### ISSUE TITLE
feature: create artifact accepts a url or a file

### ISSUE THREAD

**Issue by famarting** [Apicurio/apicurio-cli#2]
### Feature or problem description

The create artifact command can accept a URL to a file in a http server.

### Proposed solution

The same argument in the cli could be used for both a file or a URL. The CLI will have to detect if the value provided starts with `http://` or `https://`

How will it benefit the CLI and its users?
for quick tests and demo scenarios it will make easier to test the CLI

### Additional context

kubectl has feature like this.

**Comment by wtrocki** [comment]
Done
