### ISSUE TITLE
Missing Assets in releases

### ISSUE THREAD

**Issue by andreaTP** [Apicurio/apicurio-cli#7]
## Description

**Version**: `>= 0.2.0`

The automatic release process is only releasing the Sources and not the compiled binaries.

### Steps to reproduce

Check https://github.com/Apicurio/apicurio-cli/releases

### Expected vs actual behaviour

The released assets should include compiled binaries

cc. @wtrocki

**Comment by wtrocki** [comment]
Good catch. Fixed

**Comment by wtrocki** [comment]
https://github.com/Apicurio/apicurio-cli/releases/tag/v0.3.2

**Comment by andreaTP** [comment]
Thanks! 👍
